name: Build bpftools archive (arm64)

on:
  push:
    tags: [ 'v*' ]          # es. v1.1.0
  workflow_dispatch:

jobs:
  build_bpftools:
    runs-on: ubuntu-22.04
    name: Build bpftools-arm64
    timeout-minutes: 240

    steps:
      - uses: actions/checkout@v4

      # 0) swap di sicurezza
      - name: Add swap
        run: |
          sudo fallocate -l 8G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          free -h

      # 1) clone ExtendedAndroidTools (shallow)
      - name: Clone upstream
        run: git clone --depth 1 https://github.com/facebookexperimental/ExtendedAndroidTools.git .

      # 2) deps host (script originale)
      - name: Install dependencies
        run: sudo ./scripts/jammy-install-deps.sh

      # 3) scarica NDK (r26b)
      - name: Setup NDK
        run: ./scripts/download-ndk.sh

      # 4) build bpftools per arm64 (il target originale)
      - name: Build
        run: make bpftools NDK_ARCH=arm64

      # 5) carica l’artefact temporaneo (come upstream)
      - uses: actions/upload-artifact@v4
        with:
          name: bpftools-arm64.tar.gz
          path: bpftools-arm64.tar.gz

      # 6) allega alla Release (solo sui tag v*)
      - name: Upload Release asset
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: bpftools-arm64.tar.gz
          generate_release_notes: true
