name: Build & release bpftools (arm64)

on:
  push:
    tags: [ 'v*' ]          # e.g. v0.1.0
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 240      # 4 h hard-limit

    steps:
    - uses: actions/checkout@v4

    # Extra 8 GB swap to survive LLVM link step
    - name: Add swap
      run: |
        sudo fallocate -l 8G /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile
        free -h

    # Clone ExtendedAndroidTools (shallow)
    - name: Clone upstream
      run: |
        git clone --depth 1 https://github.com/facebookexperimental/ExtendedAndroidTools.git src
        echo "SRC_DIR=$PWD/src" >> $GITHUB_ENV

    # Host deps (same as upstream)
    - name: Install deps
      run: sudo $SRC_DIR/scripts/jammy-install-deps.sh

    # Download NDK once
    - name: Download NDK
      run: $SRC_DIR/scripts/download-ndk.sh

    # Build bpftools for arm64 with limited parallelism
    - name: Build bpftools (arm64)
      working-directory: ${{ env.SRC_DIR }}
      run: |
        make bpftools NDK_PATH=$PWD/android-ndk-r27b NDK_ARCH=arm64 THREADS=4
        cp bpftools-arm64.tar.gz $GITHUB_WORKSPACE/

    # Checksums
    - name: SHA256SUMS
      run: |
        cd $GITHUB_WORKSPACE
        sha256sum bpftools-arm64.tar.gz > SHA256SUMS

    # Upload as release assets (only on tag)
    - name: Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          bpftools-arm64.tar.gz
          SHA256SUMS
        generate_release_notes: true
